### ISSUE TITLE
Last page with final total is not shown anymore

### ISSUE THREAD

**Issue by Dimi1033** [cderche/shiny-rails#164]
We need back the last page with the final total, because the way we have it now, the customer does not sees what is final total is after he added the promo code. 
<img width="1280" alt="screenshot 2017-09-09 16 26 24" src="https://user-images.githubusercontent.com/22236297/30240590-e2940106-957b-11e7-9e49-fbd8d8f3ca46.png">

**Comment by cyri113** [comment]
didn't manage to put the final total back in so far as it require more work.

But put the warning in.
