### ISSUE TITLE
Additional options to current shiny

### ISSUE THREAD

**Issue by Dimi1033** [cderche/shiny-rails#68]
Add additional options

Fridge: 250 rub.
Microwave: 250 rub. 
Oven: 250 rub.
Kitchen Cabinets: 400rub.
Balcony: 450rub.
Windows: 0-4 = 1000rub,  5-8 = 1800rub, 8+ = 2500rub. 
Ironing: 0-10 = 300rub, 11-20 = 600rub, 21-30 = 1000 rub

**Comment by cyri113** [comment]
This should be done from the rails console for now.
