### ISSUE TITLE
Background picture

### ISSUE THREAD

**Issue by Dimi1033** [cderche/shiny-rails#98]
Change the background picture on the first page to a lighter picture. If needed, thange the font from whit to black.

**Comment by cyri113** [comment]
@Dimi1033 can you please use Pixelmator to remove the frames on the wall?

![screen shot 2017-04-13 at 21 53 40](https://cloud.githubusercontent.com/assets/1618640/25019568/b2c16c50-2093-11e7-9ab3-9864ca27178e.png)
